### ISSUE TITLE
Add `u.multi`

### ISSUE THREAD

**Issue by aaronjensen** [substantial/updeep#11]
This would thread multiple updates together. Again, not sure on naming. Lodash calls this `flow`. Ramda calls it `pipe`. In Clojure it's the threading operator. For `updeep` it represents multiple updates... maybe. Not necessarily though. 

Naming options:

* `thread`
* `pipe`
* `flow`
* `multi`

**Comment by ansonkao** [comment]
+1

Curious what you had in mind exactly, as I've found that the need to collate multiple updates can happen in a couple different ways. The first way is when all of the changes are to the same location, and would just be an alias to _.flow:
``` JS
var inputState = {
  fruits: [
    "Banana",
    "Orange",
    "Apple"
  ]
}

var outputState = u({
  fruits: u.multi(
    (fruits) => ["Zucchini", ...fruits],
    (fruits) => [...fruits].sort()
  )
}, inputState)

expect(outputState.fruits).to.eql(["Apple", "Banana", "Orange", "Zucchini"])
// Yes, Zucchini's are technically fruits!
```

And the second one is when the change occurs in 2 different places. I'm not sure how to implement but would look something like this:
``` JS
var inputState = {
  fruits: [
    {
      name: "Banana",
      price: 10
    },
    {
      name: "Orange",
      price: 12
    },
    {
      name: "Apple",
      price: 20
    }
  ]
}

var outputState = u.multi(
  inputState,
  u.updateIn(
    ['fruits', '*', 'name'],
    (fruit) => `${fruit}s`
  ),
  u.updateIn(
    ['fruits', '*', 'price'],
    (price) => price*2
  )
)

expect(outputState.fruits).to.eql([
  {
    name: "Bananas",
    price: 20
  },
  {
    name: "Oranges",
    price: 24
  },
  {
    name: "Apples",
    price: 40
  }
])

```

Thoughts?

**Comment by aaronjensen** [comment]
tbh, i think this falls under the same fate as the last... probably going to rely on `lodash/fp`'s flow. 

For your second example:

```js
_.flow(
  u.updateIn(
    ['fruits', '*', 'name'],
    (fruit) => `${fruit}s`
  ),
  u.updateIn(
    ['fruits', '*', 'price'],
    (price) => price*2
  )
)(inputState)
```

should give you what you want, I think.

**Comment by ansonkao** [comment]
Ahh, that currying is still fairly new to me but wow it is so magical. Tested and works beautifully. Thanks!

**Comment by aaronjensen** [comment]
No problem.

I'm going to close this out because lodash works great for this.
