### ISSUE TITLE
Add non-standalone umd build

### ISSUE THREAD

**Issue by aaronjensen** [substantial/updeep#14]
Currently the standalone build includes some of lodash. We should have a build that makes use of an existing lodash as well.

**Comment by aaronjensen** [comment]
https://github.com/megawac/babel-plugin-lodash may help

**Comment by d6u** [comment]
Don't know the context but seems like updeep already requiring individual method of lodash, shouldn't that be enough?

**Comment by aaronjensen** [comment]
Yeah, it's probably fine. The idea was to have a build that you could include along-side lodash w/o something like webpack to save a few k. not a big deal.
