### ISSUE TITLE
Confusing/inconsistent merging

### ISSUE THREAD

**Issue by wdoug** [substantial/updeep#149]
Looking at this code:
```js
updeep({ a: { b: 'value' } }, { a: 'test' })
```

I was expecting the output to be:
```js
{ a: { b: 'value' } }
```

However, the output was actually:
```js
{ a: { '0': 't', '1': 'e', '2': 's', '3': 't', b: 'value' } }
```

This seems like a bug, but just in case this was intentional, I next tried this:
```js
updeep({ a: { b: 'value' } }, { a: ['test'] })
```
Which, I would have previously expected to output:
```js
{ a: { b: 'value' } }
``` 
but after seeing the above example thought I might see something more like:
```js
{ a: ["test", b: "value"] } 
// where the value at key `a` is an array with string "test" at index 0 and a second key `b` with value "value"
// I know the above isn't valid syntax, but it is how chrome logs that particular scenario
```

It was neither, however, and instead gave:
```js
{ a: [ 'test' ] }
```

**Comment by tylermercer** [comment]
As is explained in the docs, the updates are the first parameter, not the second. The second is the object being updated. Thus, the behavior you see is correct. The weird string-to-numeric keys problem is probably because you're merging a string with an object.

**Comment by aaronjensen** [comment]
@tylermercer is correct, it looks like things are working as intended, but because the argument order is atypical in JavaScript, it is somewhat surprising. It's designed this way to support currying, but it does require learning/memorization that this is the case.
