### ISSUE TITLE
Values can't be set to undefined

### ISSUE THREAD

**Issue by DerekMaffett** [substantial/updeep#24]
Undefined doesn't seem to be considered a permissible update value:

```
u({ a: 3 }, {});
// { a: 3 }
u({ a: null });
// { a: null }
u({ a: undefined }, {});
// {}
```

Is that intentional or something that should be fixed (I can work on it if you think it makes sense)? I can see potential reasons for either way.

**Comment by aaronjensen** [comment]
I believe this was intentional, but I can't remember why. I think it's confusing though, so I'd say go for it.

**Comment by mkornblum** [comment]
I think `undefined` is not valid JSON, maybe that was the reason? Although it doesn't seem like the intention here is to always force valid JSON.

**Comment by aaronjensen** [comment]
I don't think I'm going to change this behavior, it's in direct conflict with https://github.com/substantial/updeep/issues/35 which I would consider to be more surprising. If you could think of a way to satisfy both of these test cases that doesn't resort to hackery and makes sense I'd consider it:

```js
  // currently fails
  it('can set a non-existent property to undefined', () => {
    const result = u({ a: undefined }, {});
    expect(result).to.eql({ a: undefined });
  });

  // currently passes
  it('does not update if the predicate is false', () => {
    const result = u({ x: u.if(false, 1)}, {});
    expect(result).to.eql({});
  });
```
