### ISSUE TITLE
reject object from array

### ISSUE THREAD

**Issue by anorudes** [substantial/updeep#33]
Hello, thanks for beauty lib, but i have ask.
How I can remove an object from an array?

    res = u({
      notes: u.reject({id: 10}),
    }, notes);

doesn't work

**Comment by aaronjensen** [comment]
You're welcome. 

You could reject by index like this

```js
    const result = u.reject((_, index) => index == 1, [3, 4, 5]);

    expect(result).to.eql([3, 5]);
```

There's not another shortcut right now.

**Comment by aaronjensen** [comment]
I may have misunderstood, if you want to remove an item w/ id of 10, try:

`u.reject(u.is('id', 10))`
