### ISSUE TITLE
Push?

### ISSUE THREAD

**Issue by peteruithoven** [substantial/updeep#40]
How would one push an item to an array with updeep? Or is this something that would be a good addition?

**Comment by aaronjensen** [comment]
Hi @peteruithoven,

You could do this:

```js
u({
  children: children => [...children, newChild],
}, obj)
```

or es5:

```js
u({
  children: function(children) { return children + [newChild]; },
}, obj)
```

That said, I have thought about adding `u.push`, `u.shift`, `u.pop`, `u.unshift`, etc. I think they'd make good additions.

**Comment by peteruithoven** [comment]
Clever! But yeah quite verbose. 
I really like how you allow custom functions to be called, what do you think about finding a way to give them extra arguments? Something like: 
``` javascript 
const state = {
  items: []
}
function add(items, item) {
  return [...arr, item];
}
const updated = u({items: {[add,'foo']}}, state);
// or
const updated = u({items: {add:['foo']}}, state);
// or 
const updated = u({items: {add:'foo'}}, state);
```

**Comment by aaronjensen** [comment]
That's what currying is for:

```js
const add = item => items => [...arr, item];
const updated = u({items: add('foo')}, state);
```

**Comment by mindjuice** [comment]
@aaronjensen In the curried code, I'm assuming ``..arr`` should be ``..items``, correct?

**Comment by aaronjensen** [comment]
@mindjuice yep, copied code w/ a typo :)

**Comment by peteruithoven** [comment]
Like! 
My questions are more than answered, but if someone wants to implement methods like push it could stay open.

**Comment by aaronjensen** [comment]
Great, I'll close this out. Thanks!

**Comment by aaronjensen** [comment]
Btw, if you have further questions, feel free to ping me on https://discord.gg/0ZcbPKXt5bY7zvjh

**Comment by benjohnson** [comment]
Just a note to say +1 on `u.push`, `u.shift`, `u.pop`, `u.unshift` etc methods. At first glance I expected to see them in the API. (Love updeep btw.)
