### ISSUE TITLE
Make lodash a dependency instead of a peerDependency

### ISSUE THREAD

**Issue by aaronjensen** [substantial/updeep#43]
Given that we're requiring lodash, it should probably actually be a dependency rather than a peerDependency.

**Comment by epeli** [comment]
I agree.

Updeep might bring in extra lodash but I don't think it matters too much because updeep only import the bits it uses. Another option would be to depend on the specific `lodash.<function name>` modules.

**Comment by epeli** [comment]
This prevents me from upgrading to Lodash 4 now.
