### ISSUE TITLE
Support deep updates with `updateIn`

### ISSUE THREAD

**Issue by adjohnson916** [substantial/updeep#45]
Currently `updateIn` only supports single value updates. It'd be convenient for it to support deep updates too. Especially for use with Redux + React.

**Comment by adjohnson916** [comment]
Oops, I think it does work already, my mistake.

**Comment by aaronjensen** [comment]
No problem @adjohnson916, glad you found what you were looking for. If it's not in the README, would you like to contribute an example of what you were looking for to the README so others can see it? Thanks!
