### ISSUE TITLE
Why reject instead of filter?

### ISSUE THREAD

**Issue by epeli** [substantial/updeep#47]
Arrays have a filter method so it's more familiar to JS  devs. I actually didn't even realize that there is a reject function since I just searched for filter (ctrl+f) and didn't find anything so I just assumed it doesn't exist.

**Comment by aaronjensen** [comment]
Sorry, are you asking why there is no `u.filter` and instead there is a `u.reject`? You could just do 

```js
u({ x: a => a.filter(...) }, { x: [...] })
```

since, as you mentioned, there is already a `filter` function on arrays in modern browsers.

If this is a request for a filter function, then I'd definitely accept a pull request for it or we can rename it and leave it open and consider adding it. Thanks!

**Comment by epeli** [comment]
> Sorry, are you asking why there is no u.filter and instead there is a u.reject?

Yes.

> If this is a request for a filter function, then I'd definitely accept a pull request for it

I don't think it makes sense to have both because converting from one to other is just simple as adding a `!` and one of the reasons I like this library is the fact that it has so small  API surface compared to something like Ramda.

The example you provided is exactly what I'm now using. It just doesn't support currying and feels bit weird.

So yeah I suggest removing reject and adding filter.

**Comment by aaronjensen** [comment]
> I don't think it makes sense to have both because converting from one to other is just simple as adding a `!`

I can see how it'd make sense to have `filter` only if we were only going to have one. That said, I don't think I agree that having both is unnecessary, but I also like having `if` and `unless` in a language. I think that being able to be expressive is one of the things that updeep enables and is designed for. There's a difference between filtering and rejecting when you take intent into account. It's also not as simple as `!` when using functions: `reject(someFunction)` vs `filter(x => !someFunction(x))`.

To be honest, I wonder how much surface area to expose in updeep, if it should have filter or reject or if it should just encourage usage of `lodash-fp` or maybe a separate `updeep-addons`.

**Comment by epeli** [comment]
Oh yeah, good point about the function usage but then again we could have [complement](http://ramdajs.com/0.19.0/docs/#complement) but that's a really deep rabbit hole Ramda is already exploring well.

> To be honest, I wonder how much surface area to expose in updeep.

After thinking this a bit I'm becoming to a conclusion that it should be smallest possible. If we keep putting stuff in updeep will just became a lame version of Ramda.

As was actually using Ramda earlier, but couple reasons drove me to updeep:

1, There is no `updateIn` equivalent Ramda. https://github.com/ramda/ramda/issues/1281
2. Ramda encourages pretty hardcore fp style programming which easily leads to unreadable code for many Javascript developers who are not invested in functional programming and even if they are they must learn the specifics of the Ramda API which is huge.

Also broken code using Ramda functions is often hard to debug because the exceptions are usually thrown randomly from the Ramda functions and not from the code I've written.

I'd like to see updeep as lite version of Ramda which is more verbose, but aims to stay as readable as possible to Javascript developers who only known standard Javascript. If that is pushed to the extreme I think it would only leave the default exported `u` function and `updateIn`. If any fancier things are required people could be forwarded to Ramda and/or Lodash.

**Comment by epeli** [comment]
Btw, have you noticed that lodash-fp have been moved to the lodash-archive?

https://github.com/lodash-archive

https://github.com/lodash-archive/lodash-fp

**Comment by aaronjensen** [comment]
> EDIT: Oh, they are incorporating it into lodash 4. Exiting times :)

Yes, I was about to reply with that. I may wait to make any big changes to what updeep is until I see how that all shakes out. 

updeep does a couple things differently than lodash-fp that may or may not be worth keeping:

* `u.map` will return the same object/array if nothing changes (this actually makes it slightly slower, so it's probably not actually worth trying not to change the reference.
* `u.map` works for both arrays and objects
* `u.if` and `u.ifElse` do not have equivalents in lodash and I think they're common enough to have a standard implementation of that doesn't require ramda
* All functions freeze the return on the way out in development mode, so they're usable individually w/ that safety-net.
* The curry implementation is an adapted version of the ramda implementation which is more performant on chrome.

> Ramda encourages pretty hardcore fp style programming 

I agree w/ these sentiments.

**Comment by aaronjensen** [comment]
Looks like you've been busy @epeli, after your lodash fp work I'll take a look at shrinking updeep so that lodash-fp cherry pickable modules can be used instead. Thanks!

https://github.com/substantial/updeep/pull/50

**Comment by epeli** [comment]
Yep, amongst other things :) I think the cherry-pickable modules will land in lodash 4.1.

> u.map will return the same object/array if nothing changes

That can be actually a nice performance benefit when using [React pure render](https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.4frmrihqj).

> u.map works for both arrays and objects

Lodash has separate versions for objects.

> u.if and u.ifElse do not have equivalents in lodash and I think they're common enough to have a standard implementation of that doesn't require ramda

I agree.

> All functions freeze the return on the way out in development mode, so they're usable individually w/ that safety-net.

I initially liked this a lot but now I'm thinking it's bit of a "useless opinion". Someone might find this library useful in a otherwise mutable context. As safety-net I've [this reducer wrapper in Redux](https://gist.github.com/epeli/fb03342e0735a72d93ea) which will acomplish the same thing in more comprehensive way for the Redux context.

----------------

@jdalton This discussion makes me wonder whether `update` and `updateIn` style functions have been considered for lodash at some point? I find weird if not because those are very essential when working with immutable data using vanilla JS data structures.

**Comment by jdalton** [comment]
The [request for them](https://github.com/lodash/lodash/issues/1823) is gaining traction. I expect it in a future version.

**Comment by aaronjensen** [comment]
> That can be actually a nice performance benefit when using React pure render.

Agreed, though I would guess it is rather an edge case--doing a map that has no actual effect often enough that it is a performance issue. There are other ways to solve it as well, my approach is just baked-in, but it makes the overall map function slower.

> Lodash has separate versions for objects.

Right, and I can see arguments for both having `map` handle both and having separate functions. I'm leaning towards appreciating the clarity of naming and usage that `mapValues` provides.

> As safety-net I've used this reducer wrapper in Redux which will acomplish the same thing in more comprehensive way for the Redux context.

We do a similar thing. Good idea on freezing the action too, I'll have to add that in.



> I think the cherry-pickable modules will land in lodash 4.1.

@jdalton do you have an ETA on 4.1? Thanks!

**Comment by aaronjensen** [comment]
Closing this out, we can move the discussion to https://github.com/substantial/updeep/pull/54
