### ISSUE TITLE
u.constant naming

### ISSUE THREAD

**Issue by ansonkao** [substantial/updeep#51]
I found the naming of u.constant confusing. I think it should be either u.replace or u.always.

Happy to submit a PR, if you agree, which would keep u.constant as an alias to the new name with a console.warn("Deprecated...")

**Comment by aaronjensen** [comment]
I named it after Haskell's `const`... I think though that I'll probably remove the function entirely as I address the stuff in https://github.com/substantial/updeep/issues/47 and all we need is `() => foo`

**Comment by ansonkao** [comment]
Ah interesting. I think removing it is probably the right move now that you mention it, as long as the docs have thorough examples to cover cases such as this. Others like me who are newer to FP would benefit a lot. Cheers
