### ISSUE TITLE
u.init - a way to initialize a brand new state

### ISSUE THREAD

**Issue by ansonkao** [substantial/updeep#52]
Since updeep is an immutability tool, I think it makes sense to have an initialization method to freeze a starting state. We could call this u.init perhaps, but ideally it would be the root method:

``` JS
var state = u({someKey: "Some Value"})
state.someKey = "Mutate" // ERROR
```

This would help enforce the practice of using updeep at *all points* where one might be tempted to mutate state. Thoughts?

**Comment by aaronjensen** [comment]
`u.freeze`

**Comment by aaronjensen** [comment]
Ah, it's not documented at the moment, if you'd like to add some documentation that'd be much appreciated. Thanks!

**Comment by ansonkao** [comment]
Sounds good, will do!

Any thoughts on having the functionality on the root function though? It feels right to me. If no second argument is provided, just return the first argument frozen. If a second argument is provided, behave the same as before. Keep u.freeze as an explicit alias.

**Comment by aaronjensen** [comment]
The root function is curried, it's common to do things like:

```js
const addName = u({ name: 'foo' })
addName({ ... })
```

**Comment by ansonkao** [comment]
Ah, nvm then, thanks! :)
