### ISSUE TITLE
underscore compatibility?

### ISSUE THREAD

**Issue by gilbox** [substantial/updeep#55]
Do you happen to know if updeep works fine with underscore?

**Comment by aaronjensen** [comment]
@gilbox I'm not sure what this means exactly, updeep depends on lodash for some of its functionality, but ultimately it is a separate thing. I don't see why you couldn't use underscore and updeep on the same project.

**Comment by aaronjensen** [comment]
Please feel free to open an issue if you run into any issues. Thanks!

**Comment by gilbox** [comment]
sorry i wasn't clear. What I meant was if you alias `lodash` to `underscore` will it work?

**Comment by aaronjensen** [comment]
In webpack? Probably not, updeep requires specific lodash functions. it only depends on a tiny subset of lodash, so it wouldn't be much benefit I'd think.
