### ISSUE TITLE
Use Dynamic Values in returns

### ISSUE THREAD

**Issue by Ghosh** [substantial/updeep#63]
How would you go about using dynamic values as keys when updating multiple values?

Doing something like this works:-
```
u.updateIn(`mocks.${action.id}.isUploading`, true, state);
```

However this returns an unexpected token error
```
return u({
 mocks: {
  creationStatus: 'normal',
   `${action.id}` : {
     isUploading: true
    }
  }
}, state);
```

Am I missing something here?

**Comment by aaronjensen** [comment]
Hi @Ghosh, 

Yes, that's not valid es6. You'd need to wrap it in `[]` like:

```js
return u({
 mocks: {
  creationStatus: 'normal',
  [action.id]: {
     isUploading: true
    }
  }
}, state);
```

**Comment by aaronjensen** [comment]
See "Computed property names": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

**Comment by Ghosh** [comment]
Oh I see. Thank you so much for helping out. :D

**Comment by aaronjensen** [comment]
No problem.
