### ISSUE TITLE
So what is the preferred way to empty an object?

### ISSUE THREAD

**Issue by JsseL** [substantial/updeep#70]
Let's say we have something like this:
```
let myObj = {
  subObj: {
    key: 'value',
  }
};
```
And I want to update the `subObj` to be `{}`. I guess I could use the `updeep.omit`, but that becomes pretty verbose and tasky if you have long list of keys you need to omit.

**Comment by epeli** [comment]
Just replace it with an empty one

```js
u(() => ({}), myOjb)
```

**Comment by aaronjensen** [comment]
Yep, exactly what @epeli said, thank you for answering.

If you want to be more explicit you could always use `u.constant`:

```js
u({ 
  subObj: u.constant({}) 
}, myObj)
```

**Comment by aaronjensen** [comment]
I'm going to close this out for now, but if you have any trouble or questions feel free to respond. Thanks!

**Comment by JsseL** [comment]
Thanks, and now that I look at it, [docs](https://github.com/substantial/updeep#uconstantobject) seem to cover this use case, so sorry for bothering.

**Comment by aaronjensen** [comment]
Not a problem, it's probably the most confusing part of updeep, so I totally understand.
