### ISSUE TITLE
LICENSE and authors for Remeda fork

### ISSUE THREAD

**Issue by yanick** [substantial/updeep#743]
Hi again!

So I'm almost ready to punt out the Remeda fork (https://github.com/yanick/updeep-remeda) Before I do so, I just need a thumb up from you. Since the fork is essentially building on the original updeep, I figure that keeping your name in the LICENSE and the `authors` in package.json and adding my own is the most reasonable thing to do. Do you agree?

**Comment by aaronjensen** [comment]
Yes, that's fine with me, thanks for checking.

**Comment by yanick** [comment]
No problem. Not doing it would have felt... sleazy. :-)
