### ISSUE TITLE
add typescript types

### ISSUE THREAD

**Issue by yanick** [substantial/updeep#81]
It'd be nice to have a `types.d.ts` typescript type file available for updeep.

For what it's worth, I began to play with this at https://github.com/yanick/updeep/tree/typescript  For the sake of getting a prototype working, I've switched the local `curry` for lodash's to be able to leverage their curried types. Right now, all tests are passing, but the main types are a little underwhelming (the currying makes it such that we end up with signatures that are `(any, any, any) => any`, which are a tad vague) Stll, I wanted to share my branch just in case you'd be interested, so you'd have a starting point. :-)

**Comment by yanick** [comment]
[challenges] Hell yeah. Try Typescript, they said, it'd make things easier, they said... ;-)

And gotcha for DefinitelyTyped. I'll work a little bit more to get a first iteration that is not pure hogwash, and I'll see about that.

[how to type curried functions] Yup, that's definitively the sane way to go at it. I was just delaying on the task, because laziness. :-)

**Comment by aaronjensen** [comment]
Actually, I would totally take a PR that added types to this repo as an `index.d.ts` as long as it had tests if you'd prefer to do that.

**Comment by aaronjensen** [comment]
Aye, I can't think of an example other than DefinitelyTyped right now, but it's standard to have a single test ts file that you can run against a tsconfig. It's really only validating the types do what you think rather than match the actual library. I don't think I'm quite ready to convert the whole project to typescript, but maybe someday...

**Comment by yanick** [comment]
[move errything to typescript] Heh. first writing the .d.ts seems to be a good gateway drug to the potential future port. But yeah, baby steps for sure. :-)

And dstlint seems to be what I want. https://hackernoon.com/testing-types-an-introduction-to-dtslint-b178f9b18ac8 \o/

**Comment by yanick** [comment]
Okay. Here's what I got:

https://github.com/yanick/updeep/tree/typescript-types has a first stab at `.d.ts` files for updeep. The types are in the directory `types`, and they come with a `types/test.ts` file (to run the test, do `npm run dtslint`.

Fwiw, the types themselves come from the branch https://github.com/yanick/updeep/tree/typescript -- in that branch all tests have been converted to `.ts` and they are passing.

Known TODOs:

- I have not been perfectly throughout with the curried versions of the functions, and some permutations are still missing.

- The curried types don't play well with the `u._` placeholder.

- Some curried types might not well with several curried calls without arguments (e.g., `u()()()(){ this: 1})({that: 2 })`

**Comment by aaronjensen** [comment]
This is looking great so far, thank you. Could you open a PR with your changes so I can comment inline, please?

> * I have not been perfectly throughout with the curried versions of the functions, and some permutations are still missing.

Do you have an example of one? Those that I've spot checked seem complete, but maybe I'm missing something.

> * The curried types don't play well with the `u._` placeholder.

Ah, yes, this would be tricky. It seems possible, but it definitely would add many more permutations.

> * Some curried types might not well with several curried calls without arguments (e.g., `u()()()(){ this: 1})({that: 2 })`

I think it's safe to ignore/make invalid empty calls. Though it's "valid", I don't see a point to typing it. Maybe someone will have a reason someday, but I wouldn't worry about it.

**Comment by yanick** [comment]
> This is looking great so far, thank you. Could you open a PR with your changes so I can comment inline, please?

Absolutely! Just didn't want to shove stuff your way until I knew you would actually like it. 

> I have not been perfectly throughout with the curried versions of the functions, and some permutations are still missing.
> Do you have an example of one? Those that I've spot checked seem complete, but maybe I'm missing something.

I'll find them back. I think there were cases of 3 and 4 argument cases where I did the (u,o,x) and (u,o) => (x) cases, but not the (u) => (o,x) and (u) => (o) => (x) cases because I was bored. :-)

> The curried types don't play well with the u._ placeholder.
> Ah, yes, this would be tricky. It seems possible, but it definitely would add many more permutations.

Just like with the case discussed below, that's something that I think would be fair to say "if you want to do it with types, either use anonymous functions à la `(x) => update(x, theObject)`, or flick the security off that gun and pepper `any`s where needed".

> Some curried types might not well with several curried calls without arguments (e.g., u()()()(){ this: 1})({that: 2 })
> I think it's safe to ignore/make invalid empty calls. Though it's "valid", I don't see a point to typing it. 
> Maybe someone will have a reason someday, but I wouldn't worry about it.

I feel the same. Most of the time that's not something one wants to do. And if one really wants to do it, there's always `any` that is there to allow it.

**Comment by aaronjensen** [comment]
Thanks again. I'm closing this out as I think there's nothing left to do here.
