### ISSUE TITLE
Add saucelabs testing against major browsers.

### ISSUE THREAD

**Issue by aaronjensen** [substantial/updeep#9]

**Comment by d6u** [comment]
I can help that, but first a saucelabs open source account is needed https://saucelabs.com/opensauce

**Comment by aaronjensen** [comment]
@d6u great! I've created an account, is there a guide to adding the key to an open source repo so that it is secure?

**Comment by d6u** [comment]
For travis I usually add them to travis.yml using encrypted key https://docs.travis-ci.com/user/encryption-keys/

I think you can also update env var in travis UI, that might be easier and also secure, but I never tried that.

**Comment by d6u** [comment]
FYI, this is my karma setup for sauce https://github.com/d6u/react-container-query/blob/286da856b3c6dc6dc7aed7232f29c367291f7553/karma.conf.js#L121-L130

**Comment by aaronjensen** [comment]
Nice, I added it as `SAUCELABS_API_KEY`
